apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: rabbit
spec:
  replicas: 1
  rabbitmq:
    additionalConfig: |
      log.console.level = info
    advancedConfig: |
      [
          {rabbit, [
            {consumer_timeout, undefined}
          ]}
      ].